const ENV = import.meta.env;

const FIREBASE = {
  API_KEY: ENV.VITE_FIREBASE_API_KEY,
  AUTH_DOMAIN: ENV.VITE_FIREBASE_AUTH_DOMAIN,
  PROJECT_ID: ENV.VITE_FIREBASE_PROJECT_ID,
  STORAGE_BUCKET: ENV.VITE_FIREBASE_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: ENV.VITE_FIREBASE_MESSAGING_SENDER_ID,
  APP_ID: ENV.VITE_FIREBASE_APP_ID,
}

export default FIREBASE;